name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '1.11'  # Cambia '11' por '1.11'

      - name: Build with Maven
        run: mvn package

      - name: Start Tomcat Server
        run: |
          wget https://downloads.apache.org/tomcat/tomcat-9/v9.0.52/bin/apache-tomcat-9.0.52.tar.gz
          tar -xzvf apache-tomcat-9.0.52.tar.gz
          ./apache-tomcat-9.0.52/bin/startup.sh

      - name: Deploy to Tomcat
        run: cp target/SampleTomcatApp.war apache-tomcat-9.0.52/webapps/

      - name: Wait for Tomcat to start
        run: sleep 30

      - name: Run Tests
        run: mvn test

      - name: Stop Tomcat Server
        run: ./apache-tomcat-9.0.52/bin/shutdown.sh
