name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Compile Java Code
        run: javac -d WEB-INF/classes src/main/java/com/example/HelloServlet.java

      - name: Create WEB-INF directory
        run: mkdir -p WEB-INF/lib

      - name: Copy web.xml
        run: cp src/main/webapp/WEB-INF/web.xml WEB-INF/

      - name: Package Web Application
        run: jar cvf SampleTomcatApp.war *

      - name: Start Tomcat Server
        run: |
          wget https://downloads.apache.org/tomcat/tomcat-9/v9.0.52/bin/apache-tomcat-9.0.52.tar.gz
          tar -xzvf apache-tomcat-9.0.52.tar.gz
          ./apache-tomcat-9.0.52/bin/startup.sh

      - name: Deploy to Tomcat
        run: cp SampleTomcatApp.war apache-tomcat-9.0.52/webapps/

      - name: Wait for Tomcat to start
        run: sleep 30

      - name: Run Tests
        run: |
          wget http://localhost:8080/SampleTomcatApp/HelloServlet

      - name: Stop Tomcat Server
        run: ./apache-tomcat-9.0.52/bin/shutdown.sh
